dotenv: .env
dependencies:
  # - <organization>/repo@<version> 
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'  
wallets:
  from_key: ${PRIVATE_KEY}